<?php $_helper = $this->helper('profileolabs_lengow')?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('profileolabs_lengow')->__('Génération du flux') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>

<?php echo $this->getChildHtml('store.switcher'); ?>
<?php $storeId = $this->getRequest()->getParam('store',Mage::app()->getDefaultStoreView()->getId())?>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getUrl('*/export_adminhtml_export/run',array('store'=>$storeId))?>')" type="button" class="scalable"><span><?php echo  Mage::helper('profileolabs_lengow')->__('Lengow Export') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('profileolabs_lengow')->__('Lengow export')?>
        </td>
    </tr>
    <?php $links = $_helper->getFilesGenerated() ?>
    <?php if(count($links)) :?>
	    <tr class="scope-label">
	    	<td class="scope-label"><?php echo  Mage::helper('profileolabs_lengow')->__('Vos flux')?></td>
	    	<td>
	    	<?php foreach($_helper->getFilesGenerated() as $link) : ?>
	    		<a href="<?php echo $link ?>" target="_blank"><?php echo $link ?></a><br />
	    	<?php endforeach; ?>
	    	</td>
	    </tr>
    <?php endif;?>
</table>